//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POWRS.PaymentLink.Localization.Resources.HtmlTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POWRS.PaymentLink.Localization.Resources.HtmlTemplates.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressColumn {
            get {
                return ResourceManager.GetString("AddressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All transactions.
        /// </summary>
        internal static string AllTransactionsCaption {
            get {
                return ResourceManager.GetString("AllTransactionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountColumn {
            get {
                return ResourceManager.GetString("AmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        internal static string ApprovalCodeColumn {
            get {
                return ResourceManager.GetString("ApprovalCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth...
        /// </summary>
        internal static string AuthColumn {
            get {
                return ResourceManager.GetString("AuthColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting card registration..
        /// </summary>
        internal static string AwaitingCardRegistration {
            get {
                return ResourceManager.GetString("AwaitingCardRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, {1} created paylink for you. On this &lt;a href=&quot;{2}&quot;&gt;link&lt;/a&gt; you can register card for future payments, view all transactions related to this product and also cancel this contract any time..
        /// </summary>
        internal static string AwaitingCardRegistrationBuyerMessage {
            get {
                return ResourceManager.GetString("AwaitingCardRegistrationBuyerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string BrandColumn {
            get {
                return ResourceManager.GetString("BrandColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Details.
        /// </summary>
        internal static string BuyerDetailsCaption {
            get {
                return ResourceManager.GetString("BuyerDetailsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Informations.
        /// </summary>
        internal static string BuyerInformationsColumn {
            get {
                return ResourceManager.GetString("BuyerInformationsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} initiated cancellation. If this is wrong please contact seller..
        /// </summary>
        internal static string CancellationBuyerMessage {
            get {
                return ResourceManager.GetString("CancellationBuyerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will usually happen when payment deadline expires..
        /// </summary>
        internal static string CancellationDeadlineMessage {
            get {
                return ResourceManager.GetString("CancellationDeadlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the cancellation was not initiated by you, and you want to know more details about the contract itself, please contact the seller directly at the phone number: &lt;a href=&apos;tel:{0}&apos;&gt;{0}&lt;/a&gt; or mail: &lt;a href=&apos;tel:{1}&apos;&gt;{1}&lt;/a&gt;  .
        /// </summary>
        internal static string CancellationNotInitiatedInfo {
            get {
                return ResourceManager.GetString("CancellationNotInitiatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} initiated cancellation. For more details contact seller directly..
        /// </summary>
        internal static string CancellationSellerMessage {
            get {
                return ResourceManager.GetString("CancellationSellerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Details.
        /// </summary>
        internal static string CardDetailsCaption {
            get {
                return ResourceManager.GetString("CardDetailsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card registration completed!.
        /// </summary>
        internal static string CardRegistrationCompleted {
            get {
                return ResourceManager.GetString("CardRegistrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card registration completed .
        /// </summary>
        internal static string CardRegistrationCompletedColumn {
            get {
                return ResourceManager.GetString("CardRegistrationCompletedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, your card is now registered. All payments regarding {1} will be automatically initiated by {2}. You can cancel any time on this &lt;a href=&apos;{3}&apos;&gt;link&lt;/a&gt;. .
        /// </summary>
        internal static string CardRegistrationDescription {
            get {
                return ResourceManager.GetString("CardRegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check card details and billing informations above, If something is not right, you can make changes &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt; If everything seems fine, just sit, relax, make sure that you have enough funds on the bank account and we will do the rest..
        /// </summary>
        internal static string CheckDetailsMessage {
            get {
                return ResourceManager.GetString("CheckDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityColumn {
            get {
                return ResourceManager.GetString("CityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string CodeColumn {
            get {
                return ResourceManager.GetString("CodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to know more details about this email and contract itself, please contact the seller directly at the phone number: &lt;a href=&quot;tel:{0}&quot;&gt;{0}&lt;/a&gt; or mail: &lt;a href=&quot;mailto:{1}&quot;&gt;{1}&lt;/a&gt; .
        /// </summary>
        internal static string ContactSellerMessage {
            get {
                return ResourceManager.GetString("ContactSellerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is our {0} attempt..
        /// </summary>
        internal static string CurrentAttempt {
            get {
                return ResourceManager.GetString("CurrentAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateColumn {
            get {
                return ResourceManager.GetString("DateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionColumn {
            get {
                return ResourceManager.GetString("DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal done..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailColumn {
            get {
                return ResourceManager.GetString("EmailColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once this this number exceeds, your product will automatically be cancelled, and in order to renew, you will have to contact seller directly..
        /// </summary>
        internal static string ExceedAttemptsMessage {
            get {
                return ResourceManager.GetString("ExceedAttemptsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string ExpirationDateColumn {
            get {
                return ResourceManager.GetString("ExpirationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string FailedStatus {
            get {
                return ResourceManager.GetString("FailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWRS D.O.O. BEOGRAD, Srbija.
        /// </summary>
        internal static string FooterCompany {
            get {
                return ResourceManager.GetString("FooterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2021 - {0} POWRS.
        /// </summary>
        internal static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In accordance with the provision of Article 27 of the Consumer Protection Act, you can fill out the withdrawal form from the contract &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt; .
        /// </summary>
        internal static string FooterWithdrawalNote {
            get {
                return ResourceManager.GetString("FooterWithdrawalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sad to say goodbye, we hope that you had good experience from using our platform..
        /// </summary>
        internal static string GoodbyeMessage {
            get {
                return ResourceManager.GetString("GoodbyeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked Pan.
        /// </summary>
        internal static string MaskedPanColumn {
            get {
                return ResourceManager.GetString("MaskedPanColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that maximum number of attempts is: {0}..
        /// </summary>
        internal static string MaxAttemptsNote {
            get {
                return ResourceManager.GetString("MaxAttemptsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum failed attempts number exceeded. Contract is automatically canceled after {0} retries..
        /// </summary>
        internal static string MaxPaymentAttemptsExceeded {
            get {
                return ResourceManager.GetString("MaxPaymentAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the maximum number of retries is defined by the seller..
        /// </summary>
        internal static string MaxRetriesNote {
            get {
                return ResourceManager.GetString("MaxRetriesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization number.
        /// </summary>
        internal static string OrganizationNumberColumn {
            get {
                return ResourceManager.GetString("OrganizationNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment canceled.
        /// </summary>
        internal static string PaymentCanceled {
            get {
                return ResourceManager.GetString("PaymentCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, we are sad to inform you that automatic payments for the product {1} performed by the {2} is canceled..
        /// </summary>
        internal static string PaymentCanceledMessage {
            get {
                return ResourceManager.GetString("PaymentCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment canceled..
        /// </summary>
        internal static string PaymentCanceledTitle {
            get {
                return ResourceManager.GetString("PaymentCanceledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment completed.
        /// </summary>
        internal static string PaymentCompleted {
            get {
                return ResourceManager.GetString("PaymentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, we are happy to inform you that all due payments for {1} performed by the {2} are now completed..
        /// </summary>
        internal static string PaymentCompletedMessage {
            get {
                return ResourceManager.GetString("PaymentCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string PaymentCompletedTitle {
            get {
                return ResourceManager.GetString("PaymentCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date.
        /// </summary>
        internal static string PaymentDateColumn {
            get {
                return ResourceManager.GetString("PaymentDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed.
        /// </summary>
        internal static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, we are here to inform you that payment for the product {1} failed..
        /// </summary>
        internal static string PaymentFailedMessage {
            get {
                return ResourceManager.GetString("PaymentFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next retry will happend on {0}..
        /// </summary>
        internal static string PaymentFailedNextRetryMessage {
            get {
                return ResourceManager.GetString("PaymentFailedNextRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed..
        /// </summary>
        internal static string PaymentFailedTitle {
            get {
                return ResourceManager.GetString("PaymentFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment not performed.
        /// </summary>
        internal static string PaymentNotPerformed {
            get {
                return ResourceManager.GetString("PaymentNotPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, we are here to inform you that card registration for the {1} requested by the {1} is not performed..
        /// </summary>
        internal static string PaymentNotPerformedMessage {
            get {
                return ResourceManager.GetString("PaymentNotPerformedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment not performed..
        /// </summary>
        internal static string PaymentNotPerformedTitle {
            get {
                return ResourceManager.GetString("PaymentNotPerformedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string PaymentReferenceColumn {
            get {
                return ResourceManager.GetString("PaymentReferenceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumberColumn {
            get {
                return ResourceManager.GetString("PhoneNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (Vat included) .
        /// </summary>
        internal static string PriceWithVatColumn {
            get {
                return ResourceManager.GetString("PriceWithVatColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product details .
        /// </summary>
        internal static string ProductDetailsColumn {
            get {
                return ResourceManager.GetString("ProductDetailsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded.
        /// </summary>
        internal static string RefundedStatus {
            get {
                return ResourceManager.GetString("RefundedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number.
        /// </summary>
        internal static string RemoteIdColumn {
            get {
                return ResourceManager.GetString("RemoteIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry, we will try again few times in a next few days and will let you know how it went....
        /// </summary>
        internal static string RetryMessage {
            get {
                return ResourceManager.GetString("RetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Informations.
        /// </summary>
        internal static string SellerInformationsColumn {
            get {
                return ResourceManager.GetString("SellerInformationsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is generated for {0} to registar card for future payment..
        /// </summary>
        internal static string StateChangedAwaitingCardRegistrationDescription {
            get {
                return ResourceManager.GetString("StateChangedAwaitingCardRegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer will be charged {0} {1} in order to register card. After card registration, funds will be automatically refunded, and card will be saved for future payments untill the end of the contract..
        /// </summary>
        internal static string StateChangedAwaitingCardRegistrationRefundDescription {
            get {
                return ResourceManager.GetString("StateChangedAwaitingCardRegistrationRefundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, change happened for payment created for {0}..
        /// </summary>
        internal static string StateChangedDescription {
            get {
                return ResourceManager.GetString("StateChangedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State changed.
        /// </summary>
        internal static string StateChangedLabel {
            get {
                return ResourceManager.GetString("StateChangedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code.
        /// </summary>
        internal static string StatusCodeColumn {
            get {
                return ResourceManager.GetString("StatusCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusColumn {
            get {
                return ResourceManager.GetString("StatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax number.
        /// </summary>
        internal static string TaxNumberColumn {
            get {
                return ResourceManager.GetString("TaxNumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Vaulter..
        /// </summary>
        internal static string ThankYouMessage {
            get {
                return ResourceManager.GetString("ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total .
        /// </summary>
        internal static string TotalColumn {
            get {
                return ResourceManager.GetString("TotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payments.
        /// </summary>
        internal static string TotalPaymentsColumn {
            get {
                return ResourceManager.GetString("TotalPaymentsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction details .
        /// </summary>
        internal static string TransactionDetailsColumn {
            get {
                return ResourceManager.GetString("TransactionDetailsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the details about completed/failed transactions will be visible in the table below. If you have any question please contact seller directly..
        /// </summary>
        internal static string TransactionsInfoMessage {
            get {
                return ResourceManager.GetString("TransactionsInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string WebsiteColumn {
            get {
                return ResourceManager.GetString("WebsiteColumn", resourceCulture);
            }
        }
    }
}
