//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POWRS.PaymentLink.Localization.Resources.Payout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POWRS.PaymentLink.Localization.Resources.Payout.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select bank account. Balance is not sufficient..
        /// </summary>
        internal static string AccountNotSelectable {
            get {
                return ResourceManager.GetString("AccountNotSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected account is: {0}. Are you sure?.
        /// </summary>
        internal static string AccountSelectionConfirmation {
            get {
                return ResourceManager.GetString("AccountSelectionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity number.
        /// </summary>
        internal static string ActivityCode {
            get {
                return ResourceManager.GetString("ActivityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &apos;Pay Now&apos; and proceeding to the IPS scan payment method, you confirm that you have read and agree to the Vaulter Terms and.
        /// </summary>
        internal static string AgreeToTerms {
            get {
                return ResourceManager.GetString("AgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &apos;Pay Now&apos; you confirm that you have read and agree to the Vaulter Terms and.
        /// </summary>
        internal static string AgreeToTermsAgain {
            get {
                return ResourceManager.GetString("AgreeToTermsAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string AlreadyPaidLabel {
            get {
                return ResourceManager.GetString("AlreadyPaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting For Payment.
        /// </summary>
        internal static string AwaitingPayment {
            get {
                return ResourceManager.GetString("AwaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account balance is visible only to you. We are not viewing or saving this information.
        /// </summary>
        internal static string BankAccountPrivacy {
            get {
                return ResourceManager.GetString("BankAccountPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank-ID Authorization.
        /// </summary>
        internal static string BankIDAuthorization {
            get {
                return ResourceManager.GetString("BankIDAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing details.
        /// </summary>
        internal static string BillingDetailsLabel {
            get {
                return ResourceManager.GetString("BillingDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string BusinessActivity {
            get {
                return ResourceManager.GetString("BusinessActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment canceled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string CardBrandLabel {
            get {
                return ResourceManager.GetString("CardBrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name on card.
        /// </summary>
        internal static string CardFullName {
            get {
                return ResourceManager.GetString("CardFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string CardNumberLabel {
            get {
                return ResourceManager.GetString("CardNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder name.
        /// </summary>
        internal static string CardOwnerName {
            get {
                return ResourceManager.GetString("CardOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card payment.
        /// </summary>
        internal static string CardPayment {
            get {
                return ResourceManager.GetString("CardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your personal-number! This information will not be stored and it&apos;s purpose is to initate bank-id authorization..
        /// </summary>
        internal static string EnterPersonalNumber {
            get {
                return ResourceManager.GetString("EnterPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        internal static string ExpiryDateLabel {
            get {
                return ResourceManager.GetString("ExpiryDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string FailedLabel {
            get {
                return ResourceManager.GetString("FailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrs D.O.O. Beograd, (org.no 21761818), Balkanska 2, Beograd.
        /// </summary>
        internal static string FooterCompanyInfo1 {
            get {
                return ResourceManager.GetString("FooterCompanyInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia ©2021 - {0} POWRS.
        /// </summary>
        internal static string FooterCompanyInfo2 {
            get {
                return ResourceManager.GetString("FooterCompanyInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and Last name.
        /// </summary>
        internal static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATE IPS QR.
        /// </summary>
        internal static string GenerateIpsQr {
            get {
                return ResourceManager.GetString("GenerateIpsQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, Welcome to smart payments.
        /// </summary>
        internal static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuals.
        /// </summary>
        internal static string Individuals {
            get {
                return ResourceManager.GetString("Individuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct payment from your bank account.
        /// </summary>
        internal static string InstantBankPayment {
            get {
                return ResourceManager.GetString("InstantBankPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal number not in valid format..
        /// </summary>
        internal static string InvalidPersonalNumber {
            get {
                return ResourceManager.GetString("InvalidPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string LeftToPayLabel {
            get {
                return ResourceManager.GetString("LeftToPayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal entities.
        /// </summary>
        internal static string LegalEntitiesOrEntrepreneurs {
            get {
                return ResourceManager.GetString("LegalEntitiesOrEntrepreneurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the mbanking application installed on your mobile device, scan the displayed one-time IPS QR code and make the payment in the environment of your bank. Information about the outcome of the payment will be shown to you immediately after the processing is completed, but it will also be delivered to your e-mail address along with the purchase confirmation..
        /// </summary>
        internal static string MbankingInstructions {
            get {
                return ResourceManager.GetString("MbankingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payments yet....
        /// </summary>
        internal static string NoPaymentsLabel {
            get {
                return ResourceManager.GetString("NoPaymentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of installments.
        /// </summary>
        internal static string NumberOfPaymentsLabel {
            get {
                return ResourceManager.GetString("NumberOfPaymentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pay with this bank, please open the payment link on the phone where you have intalled Bank-ID..
        /// </summary>
        internal static string OpenPaymentLinkOnPhone {
            get {
                return ResourceManager.GetString("OpenPaymentLinkOnPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other payment methods.
        /// </summary>
        internal static string OtherPaymentMethods {
            get {
                return ResourceManager.GetString("OtherPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string PaidLabel {
            get {
                return ResourceManager.GetString("PaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer details.
        /// </summary>
        internal static string PayerDetails {
            get {
                return ResourceManager.GetString("PayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment details.
        /// </summary>
        internal static string PaymentDetails {
            get {
                return ResourceManager.GetString("PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Not Performed.
        /// </summary>
        internal static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment history.
        /// </summary>
        internal static string PaymentHistoryLabel {
            get {
                return ResourceManager.GetString("PaymentHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is in progress... Do not refresh the page!.
        /// </summary>
        internal static string PaymentInProgress {
            get {
                return ResourceManager.GetString("PaymentInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment link has expired. Please contact the seller to receive a new one..
        /// </summary>
        internal static string PaymentLinkExpired {
            get {
                return ResourceManager.GetString("PaymentLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment link has expired. Please contact the seller to receive a new one..
        /// </summary>
        internal static string PaymentLinkExpiredAgain {
            get {
                return ResourceManager.GetString("PaymentLinkExpiredAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment could not be completed. Please try again or use different bank account..
        /// </summary>
        internal static string PaymentNotPossible {
            get {
                return ResourceManager.GetString("PaymentNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the outcome of the payment will be shown to you immediately after the processing is completed, but it will also be delivered to your e-mail address along with the purchase confirmation..
        /// </summary>
        internal static string PaymentOutcomeInfo {
            get {
                return ResourceManager.GetString("PaymentOutcomeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment summary.
        /// </summary>
        internal static string PaymentOverview {
            get {
                return ResourceManager.GetString("PaymentOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to pay.
        /// </summary>
        internal static string PaymentRemaining {
            get {
                return ResourceManager.GetString("PaymentRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Completed.
        /// </summary>
        internal static string PaymentSuccessful {
            get {
                return ResourceManager.GetString("PaymentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment completed. You will be transfered to seller page shortly....
        /// </summary>
        internal static string PaymentSuccessfulRedirect {
            get {
                return ResourceManager.GetString("PaymentSuccessfulRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successful. Thank you for using vaulter!.
        /// </summary>
        internal static string PaymentSuccessfulThankYou {
            get {
                return ResourceManager.GetString("PaymentSuccessfulThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment failed..
        /// </summary>
        internal static string PaymentUnsuccessful {
            get {
                return ResourceManager.GetString("PaymentUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Failed. You will be transfered to seller page shortly....
        /// </summary>
        internal static string PaymentUnsuccessfulRedirect {
            get {
                return ResourceManager.GetString("PaymentUnsuccessfulRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with your mbanking app.
        /// </summary>
        internal static string PayWithMbanking {
            get {
                return ResourceManager.GetString("PayWithMbanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string PendingLabel {
            get {
                return ResourceManager.GetString("PendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect your money with smart payments.
        /// </summary>
        internal static string ProtectWithVaulter {
            get {
                return ResourceManager.GetString("ProtectWithVaulter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize recipient.
        /// </summary>
        internal static string RecipientAuthorization {
            get {
                return ResourceManager.GetString("RecipientAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be redirected to seller page shortly....
        /// </summary>
        internal static string RedirectToSellerPage {
            get {
                return ResourceManager.GetString("RedirectToSellerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded.
        /// </summary>
        internal static string Refunded {
            get {
                return ResourceManager.GetString("Refunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded.
        /// </summary>
        internal static string RefundedLabel {
            get {
                return ResourceManager.GetString("RefundedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate the IPS QR CODE.
        /// </summary>
        internal static string RegenerateIpsQrCode {
            get {
                return ResourceManager.GetString("RegenerateIpsQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new card.
        /// </summary>
        internal static string RegisterNewCard {
            get {
                return ResourceManager.GetString("RegisterNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization number.
        /// </summary>
        internal static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold by.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Agreement.
        /// </summary>
        internal static string SalesContract {
            get {
                return ResourceManager.GetString("SalesContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved card.
        /// </summary>
        internal static string SavedCardLabel {
            get {
                return ResourceManager.GetString("SavedCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the following IPS QR-code with your Bank-ID app..
        /// </summary>
        internal static string ScanIPSQRCode {
            get {
                return ResourceManager.GetString("ScanIPSQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the following IPS QR- code with your BANK-ID app, or click on it if your Bank-ID is installed on your computer.
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a bank.
        /// </summary>
        internal static string SelectBank {
            get {
                return ResourceManager.GetString("SelectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        internal static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Delivery.
        /// </summary>
        internal static string ServiceProvision {
            get {
                return ResourceManager.GetString("ServiceProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired, refresh the page to try again..
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Num.
        /// </summary>
        internal static string TaxID {
            get {
                return ResourceManager.GetString("TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        internal static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your billing..
        /// </summary>
        internal static string ThankYouForPayment {
            get {
                return ResourceManager.GetString("ThankYouForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time&apos;s up.
        /// </summary>
        internal static string TimeExpired {
            get {
                return ResourceManager.GetString("TimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total to pay.
        /// </summary>
        internal static string TotalAmountDue {
            get {
                return ResourceManager.GetString("TotalAmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction cancelled..
        /// </summary>
        internal static string TransactionCanceled {
            get {
                return ResourceManager.GetString("TransactionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your transaction cannot be completed..
        /// </summary>
        internal static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction completed successfully..
        /// </summary>
        internal static string TransactionSuccessful {
            get {
                return ResourceManager.GetString("TransactionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is completed but card is not valid long enough. Card must be valid at least until {0}. Same amount will be refunded to your account automatically. Please try with different card..
        /// </summary>
        internal static string TransactionSuccessfulCardNotValid {
            get {
                return ResourceManager.GetString("TransactionSuccessfulCardNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Payment.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount safeguarded by Vaulter until the end of the cancelation period set by the seller.
        /// </summary>
        internal static string VaultAmountHeld {
            get {
                return ResourceManager.GetString("VaultAmountHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaulter service fee.
        /// </summary>
        internal static string VaulterFee {
            get {
                return ResourceManager.GetString("VaulterFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Vaulter checkout.
        /// </summary>
        internal static string WelcomeToVaulterPayment {
            get {
                return ResourceManager.GetString("WelcomeToVaulterPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT 20%.
        /// </summary>
        internal static string WithVAT {
            get {
                return ResourceManager.GetString("WithVAT", resourceCulture);
            }
        }
    }
}
